#ifndef CONTROL_CONTROLLERTUNING_TUNING_INTERFACE_H_
#define CONTROL_CONTROLLERTUNING_TUNING_INTERFACE_H_


void tuning_Init(void);

void tuning_Process(void);

#endif /* CONTROL_CONTROLLERTUNING_TUNING_INTERFACE_H_ */
