# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT BOOT_FLASH CACHE STRING "Type of multi-context")
#-----------------------Build FSBL Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*FSBL.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " FSBL)
    ExternalProject_Add(robonaut-firmware_FSBL
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/FSBL/build/${CMAKE_BUILD_TYPE}
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/FSBL
        PREFIX                      FSBL
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/FSBL/build/${CMAKE_BUILD_TYPE}")
endif()
#-----------------------Build Appli Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*Appli.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " Appli)
    ExternalProject_Add(robonaut-firmware_Appli
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/Appli/build/${CMAKE_BUILD_TYPE}
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/Appli
        PREFIX                      Appli
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/Appli/build/${CMAKE_BUILD_TYPE}")
endif()

